#Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.
termo=input('Digite algo:')
print('O tipo primitivo do termo é ',type(termo))
print('Só tem espaços? ',termo.isspace())
print('É um número? ', termo.isnumeric())
print('É alfabetico?', termo.isalpha())
print('É alfanumérico? ', termo.isalnum())
print('Está em maiúsculas? ', termo.isupper())
print('Está em minúsculas? ', termo.islower())
print('Está capitalizada? ', termo.istitle())
#o 'termo' é o objeto
print('O tipo primitivo do termo é {}'.format(type(termo)))
print('Só tem espaços? {}'.format(termo.isspace()))
print('É um número? {}'.format(termo.isnumeric()))
print('É alfabetico? {}'.format(termo.isalpha()))
print('É alfanumérico? {}'.format(termo.isalnum()))
print('Está em maiúsculas? {}'.format(termo.isupper()))
print('Está em minúsculas? {}'.format(termo.islower()))
print('Está capitalizada? {}'.format(termo.istitle()))